# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cards.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_cards.ipynb 2
from nbdev.showdoc import *
from fastcore.test import *
from fastcore.utils import *

# %% ../nbs/00_cards.ipynb 3
suits = ["♣️", "♦️", "❤️", "♠️"]
ranks=[None,"A"] +[str(x) for x in range(2,11)]+['J','Q','K']


# %% ../nbs/00_cards.ipynb 8
class Card:
    "A playing Card"
    def __init__(self, suit:int, rank:int):
        self.suit, self.rank = suit, rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__=__str__

# %% ../nbs/00_cards.ipynb 14
@patch
def __eq__(self:Card, a:Card): return (self.suit, self.rank) == (a.suit, a.rank)

# %% ../nbs/00_cards.ipynb 17
@patch
def __lt__(self:Card, a:Card): return (self.suit, self.rank) < (a.suit, a.rank)

# %% ../nbs/00_cards.ipynb 19
@patch
def __gt__(self:Card, a:Card): return (self.suit, self.rank) > (a.suit, a.rank)
